### ISSUE TITLE
Возможность передать nullptr вместо указателя на стек в функцию stackPush №1

### ISSUE THREAD

**Issue by h0lycookie** [Gaussiandra/Safe-stack#1]
```
int main() {
    stack_t stack1;
    stackCtor(stack1);

    for (stackElementType i = 0; i < 10; ++i) {
        stackPush(nullptr, i);
    }

    stackElementType value;
    for (stackElementType i = 0; i < 8; ++i) {
        stackPop(&stack1, &value);
    }

    stackDtor(&stack1);

    printf("All is good\n");
    return 0;
}
```
Приводит к тому, что в консоль не выводится "All is good" и функцией stackDump не выводится сообщение, т.е. в программе ошибка.

![error](https://user-images.githubusercontent.com/89473962/135815439-98515859-cd3b-4177-bf5b-8234c10dc3e1.png)

**Comment by Gaussiandra** [comment]
Исправлю.

**Comment by Gaussiandra** [comment]
Исправлено. 
https://github.com/Gaussiandra/SaveStack/commit/252c6541bda3f83520b80ec9744079916b350128
